
--define:sigeo_use_float64
--define:sigeo_return_zero_when_angle_between_zeroLen_vectors
--define:sigeo_return_axisX_when_zeroLen_normal_vector
--define:sigeo_return_small_curve_when_costructed_curve_has_zero_length


